# Generated by Django 3.0.3 on 2020-03-01 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_book_img'),
        ('core', '0003_auto_20200301_2044'),
    ]

    operations = [
    ]
